"""P2 atomic resolutions, review and immutable interpretation maintenance history."""
NAME = "m0008_resolutions"
VERSION = 8
STATEMENTS = (
    """CREATE TABLE resolutions (resolution_id TEXT PRIMARY KEY,
        source_event_id TEXT NOT NULL REFERENCES events(event_id),
        interpretation_id TEXT NOT NULL REFERENCES interpretations(interpretation_id),
        command_event_id TEXT NOT NULL UNIQUE REFERENCES events(event_id),
        actor_id TEXT NOT NULL REFERENCES actors(actor_id),
        policy_version TEXT NOT NULL,
        request_hash TEXT NOT NULL,
        expected_context_json TEXT NOT NULL CHECK(json_valid(expected_context_json)),
        context_digest TEXT NOT NULL,
        plan_json TEXT NOT NULL CHECK(json_valid(plan_json)),
        created_at TEXT NOT NULL)""",
    """CREATE TABLE resolution_results (resolution_id TEXT PRIMARY KEY REFERENCES resolutions(resolution_id),
        disposition TEXT NOT NULL CHECK(disposition IN ('APPLIED','PENDING_REVIEW','NO_ACTION','SOURCE_REPLAYED')),
        result_json TEXT NOT NULL CHECK(json_valid(result_json)),
        completed_at TEXT NOT NULL)""",
    """CREATE TABLE resolution_request_keys (actor_id TEXT NOT NULL REFERENCES actors(actor_id),
        idempotency_key TEXT NOT NULL,
        request_hash TEXT NOT NULL,
        resolution_id TEXT NOT NULL REFERENCES resolutions(resolution_id),
        PRIMARY KEY(actor_id,idempotency_key))""",
    """CREATE TABLE source_applications (source_event_id TEXT PRIMARY KEY REFERENCES events(event_id),
        canonical_resolution_id TEXT NOT NULL UNIQUE REFERENCES resolutions(resolution_id),
        applied_at TEXT NOT NULL)""",
    """CREATE TABLE source_application_changes (source_event_id TEXT NOT NULL REFERENCES events(event_id),
        previous_resolution_id TEXT NOT NULL REFERENCES resolutions(resolution_id),
        new_resolution_id TEXT NOT NULL UNIQUE REFERENCES resolutions(resolution_id),
        command_event_id TEXT NOT NULL UNIQUE REFERENCES events(event_id),
        reason TEXT NOT NULL,
        actor_id TEXT NOT NULL REFERENCES actors(actor_id),
        created_at TEXT NOT NULL,
        PRIMARY KEY(source_event_id,previous_resolution_id))""",
    """CREATE TABLE resolution_source_bindings (binding_event_id TEXT PRIMARY KEY REFERENCES events(event_id),
        source_event_id TEXT NOT NULL REFERENCES events(event_id),
        interpretation_id TEXT NOT NULL REFERENCES interpretations(interpretation_id),
        resolution_id TEXT NOT NULL REFERENCES resolutions(resolution_id),
        task_id TEXT NOT NULL REFERENCES tasks(task_id),
        UNIQUE(resolution_id,task_id))""",
    """CREATE TABLE reviews (review_id TEXT PRIMARY KEY,
        resolution_id TEXT NOT NULL UNIQUE REFERENCES resolutions(resolution_id),
        status TEXT NOT NULL CHECK(status IN ('PENDING','APPROVED','REJECTED','SOURCE_REPLAYED')),
        revision INTEGER NOT NULL CHECK(revision>=1),
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL)""",
    """CREATE TABLE review_changes (command_event_id TEXT PRIMARY KEY REFERENCES events(event_id),
        review_id TEXT NOT NULL REFERENCES reviews(review_id),
        from_revision INTEGER NOT NULL CHECK(from_revision>=1),
        to_revision INTEGER NOT NULL CHECK(to_revision=from_revision+1),
        action TEXT NOT NULL CHECK(action IN ('APPROVE','REJECT')),
        actor_id TEXT NOT NULL REFERENCES actors(actor_id),
        reason TEXT NOT NULL,
        context_json TEXT NOT NULL CHECK(json_valid(context_json)),
        result_json TEXT NOT NULL CHECK(json_valid(result_json)),
        created_at TEXT NOT NULL,
        UNIQUE(review_id,to_revision))""",
    """CREATE TABLE maintenance_heads (root_interpretation_id TEXT PRIMARY KEY REFERENCES interpretations(interpretation_id),
        current_interpretation_id TEXT NOT NULL REFERENCES interpretations(interpretation_id),
        status TEXT NOT NULL CHECK(status IN ('NORMAL','CORRECTED','REJECTED','RERUN_PENDING')),
        revision INTEGER NOT NULL CHECK(revision>=1),
        pending_operation_event_id TEXT REFERENCES events(event_id),
        pending_child_interpretation_id TEXT REFERENCES interpretations(interpretation_id),
        updated_at TEXT NOT NULL,
        CHECK((status='RERUN_PENDING' AND pending_operation_event_id IS NOT NULL AND pending_child_interpretation_id IS NOT NULL) OR (status!='RERUN_PENDING' AND pending_operation_event_id IS NULL AND pending_child_interpretation_id IS NULL)))""",
    """CREATE TABLE interpretation_changes (operation_event_id TEXT NOT NULL REFERENCES events(event_id),
        root_interpretation_id TEXT NOT NULL REFERENCES interpretations(interpretation_id),
        parent_interpretation_id TEXT NOT NULL REFERENCES interpretations(interpretation_id),
        child_interpretation_id TEXT REFERENCES interpretations(interpretation_id),
        action TEXT NOT NULL CHECK(action IN ('CORRECT','REJECT','RERUN','RERUN_COMPLETE')),
        actor_id TEXT NOT NULL REFERENCES actors(actor_id),
        reason TEXT NOT NULL,
        from_revision INTEGER NOT NULL CHECK(from_revision>=1),
        to_revision INTEGER NOT NULL CHECK(to_revision=from_revision+1),
        created_at TEXT NOT NULL,
        PRIMARY KEY(root_interpretation_id,to_revision))""",
    """CREATE TABLE interpretation_operation_completions (operation_event_id TEXT PRIMARY KEY REFERENCES events(event_id),
        child_interpretation_id TEXT NOT NULL UNIQUE REFERENCES interpretations(interpretation_id),
        processing_status TEXT NOT NULL CHECK(processing_status IN ('EXTRACTED','FAILED','INTERRUPTED')),
        head_applied INTEGER NOT NULL CHECK(head_applied IN (0,1)),
        expected_head_revision INTEGER NOT NULL CHECK(expected_head_revision>=1),
        observed_head_revision INTEGER NOT NULL CHECK(observed_head_revision>=1),
        completed_at TEXT NOT NULL,
        result_json TEXT NOT NULL CHECK(json_valid(result_json)))""",
    """CREATE TABLE maintenance_request_keys (actor_id TEXT NOT NULL REFERENCES actors(actor_id),
        idempotency_key TEXT NOT NULL,
        request_hash TEXT NOT NULL,
        operation_event_id TEXT NOT NULL REFERENCES events(event_id),
        result_json TEXT NOT NULL CHECK(json_valid(result_json)),
        PRIMARY KEY(actor_id,idempotency_key))""",
    """CREATE TABLE review_request_keys (actor_id TEXT NOT NULL REFERENCES actors(actor_id),
        idempotency_key TEXT NOT NULL,
        request_hash TEXT NOT NULL,
        command_event_id TEXT NOT NULL REFERENCES events(event_id),
        result_json TEXT NOT NULL CHECK(json_valid(result_json)),
        PRIMARY KEY(actor_id,idempotency_key))""",
    """CREATE TRIGGER resolutions_no_update BEFORE UPDATE ON resolutions BEGIN SELECT RAISE(ABORT,'resolutions is append-only'); END""",
    """CREATE TRIGGER resolutions_no_delete BEFORE DELETE ON resolutions BEGIN SELECT RAISE(ABORT,'resolutions is append-only'); END""",
    """CREATE TRIGGER resolution_results_no_update BEFORE UPDATE ON resolution_results BEGIN SELECT RAISE(ABORT,'resolution_results is append-only'); END""",
    """CREATE TRIGGER resolution_results_no_delete BEFORE DELETE ON resolution_results BEGIN SELECT RAISE(ABORT,'resolution_results is append-only'); END""",
    """CREATE TRIGGER resolution_request_keys_no_update BEFORE UPDATE ON resolution_request_keys BEGIN SELECT RAISE(ABORT,'resolution_request_keys is append-only'); END""",
    """CREATE TRIGGER resolution_request_keys_no_delete BEFORE DELETE ON resolution_request_keys BEGIN SELECT RAISE(ABORT,'resolution_request_keys is append-only'); END""",
    """CREATE TRIGGER source_applications_no_update BEFORE UPDATE ON source_applications BEGIN SELECT RAISE(ABORT,'source_applications is append-only'); END""",
    """CREATE TRIGGER source_applications_no_delete BEFORE DELETE ON source_applications BEGIN SELECT RAISE(ABORT,'source_applications is append-only'); END""",
    """CREATE TRIGGER source_application_changes_no_update BEFORE UPDATE ON source_application_changes BEGIN SELECT RAISE(ABORT,'source_application_changes is append-only'); END""",
    """CREATE TRIGGER source_application_changes_no_delete BEFORE DELETE ON source_application_changes BEGIN SELECT RAISE(ABORT,'source_application_changes is append-only'); END""",
    """CREATE TRIGGER resolution_source_bindings_no_update BEFORE UPDATE ON resolution_source_bindings BEGIN SELECT RAISE(ABORT,'resolution_source_bindings is append-only'); END""",
    """CREATE TRIGGER resolution_source_bindings_no_delete BEFORE DELETE ON resolution_source_bindings BEGIN SELECT RAISE(ABORT,'resolution_source_bindings is append-only'); END""",
    """CREATE TRIGGER review_changes_no_update BEFORE UPDATE ON review_changes BEGIN SELECT RAISE(ABORT,'review_changes is append-only'); END""",
    """CREATE TRIGGER review_changes_no_delete BEFORE DELETE ON review_changes BEGIN SELECT RAISE(ABORT,'review_changes is append-only'); END""",
    """CREATE TRIGGER interpretation_changes_no_update BEFORE UPDATE ON interpretation_changes BEGIN SELECT RAISE(ABORT,'interpretation_changes is append-only'); END""",
    """CREATE TRIGGER interpretation_changes_no_delete BEFORE DELETE ON interpretation_changes BEGIN SELECT RAISE(ABORT,'interpretation_changes is append-only'); END""",
    """CREATE TRIGGER interpretation_operation_completions_no_update BEFORE UPDATE ON interpretation_operation_completions BEGIN SELECT RAISE(ABORT,'interpretation_operation_completions is append-only'); END""",
    """CREATE TRIGGER interpretation_operation_completions_no_delete BEFORE DELETE ON interpretation_operation_completions BEGIN SELECT RAISE(ABORT,'interpretation_operation_completions is append-only'); END""",
    """CREATE TRIGGER maintenance_request_keys_no_update BEFORE UPDATE ON maintenance_request_keys BEGIN SELECT RAISE(ABORT,'maintenance_request_keys is append-only'); END""",
    """CREATE TRIGGER maintenance_request_keys_no_delete BEFORE DELETE ON maintenance_request_keys BEGIN SELECT RAISE(ABORT,'maintenance_request_keys is append-only'); END""",
    """CREATE TRIGGER review_request_keys_no_update BEFORE UPDATE ON review_request_keys BEGIN SELECT RAISE(ABORT,'review_request_keys is append-only'); END""",
    """CREATE TRIGGER review_request_keys_no_delete BEFORE DELETE ON review_request_keys BEGIN SELECT RAISE(ABORT,'review_request_keys is append-only'); END""",
)
